### ISSUE TITLE
Better Library handling in the config

### ISSUE THREAD

**Issue by JonnyOnlineYT** [skidfuscatordev/skidfuscator-java-obfuscator#37]
im probably to dumb to know what im doing wrong xd

i just like wanna do "libs/*" to add all librarys from a folder cuz i have like 14

**Comment by LouissXI** [comment]
Hi,
Please open a ticket on our [Discord](https://discord.gg/QJC9g8fBU9) for further help.
Sincerly, Louis.

**Comment by ChromMob** [comment]
Just specify the argument li=<folder_with_the_libs>

**Comment by ChromMob** [comment]
https://discord.gg/QJC9g8fBU9 << the discord in case you are not in already

**Comment by JonnyOnlineYT** [comment]
> Just specify the argument li=<folder_with_the_libs>

yea i figured it out

**Comment by ChromMob** [comment]
I would recommend joining the discord still even if you figured it out. You will get fast info on updates and ability to buy the premium version which is much better.
