### ISSUE TITLE
Driver class ambiguity in multiple obfuscated jars

### ISSUE THREAD

**Issue by sadikakbulut** [skidfuscatordev/skidfuscator-java-obfuscator#42]
I have a project with multiple libraries, I can obfuscate each library one by one. But when I try to run the application it fails with the following error message.

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
at skid.Driver.get(CacheTemplate.java:18)

The problem is that there are multiple skid/Driver classes in the classpath and the classloader loads the first one it finds in the classpath.

My current workaround is adding,

**driver: false**

to the config file.

A possible solution would be setting the driver name in the configuration file or at least appending the input jar name (xxx.jar) to the Driver class name as Driver_xxx.

**Comment by terminalsin** [comment]
Fixed in 2.0.7. Added the possibility to rename the driver to whatever you wish. Edit the driver name with:

```
driver: {
    enabled: true
    path: "my/class/Name"
}
```
