### ISSUE TITLE
Crash when having multiple jars with the same skid/Factory class

### ISSUE THREAD

**Issue by dm94** [skidfuscatordev/skidfuscator-java-obfuscator#48]
One of the projects I'm working on has the option to load jars as plugins.

The problem is that when loading these jars if several have used this obfuscator they fail because they share the same class in the same package (skid/Factory).

Is there a way for the package or class to be called differently?

**Comment by terminalsin** [comment]
Will be fixed in the next update

**Comment by terminalsin** [comment]
Fixed in latest

**Comment by PEUNTL** [comment]
> Fixed in latest

I downloaded 2.0.7 and it didn't fix it

**Comment by terminalsin** [comment]
> > Fixed in latest
> 
> I downloaded 2.0.7 and it didn't fix it

thats because latest isn't released...

**Comment by PEUNTL** [comment]
> > > Fixed in latest
> > 
> > 
> > I downloaded 2.0.7 and it didn't fix it
> 
> thats because latest isn't released...

....Sorry, how do I download it? .

**Comment by terminalsin** [comment]
> > > > Fixed in latest
> > > 
> > > 
> > > I downloaded 2.0.7 and it didn't fix it
> > 
> > 
> > thats because latest isn't released...
> 
> ....Sorry, how do I download it? .

You can compile the latest source from the github or wait for the next github release

**Comment by PEUNTL** [comment]
> > > > > Fixed in latest
> > > > 
> > > > 
> > > > I downloaded 2.0.7 and it didn't fix it
> > > 
> > > 
> > > thats because latest isn't released...
> > 
> > 
> > ....Sorry, how do I download it? .
> 
> You can compile the latest source from the github or wait for the next github release

thank you very much

**Comment by PEUNTL** [comment]
> > > > > Fixed in latest
> > > > 
> > > > 
> > > > I downloaded 2.0.7 and it didn't fix it
> > > 
> > > 
> > > thats because latest isn't released...
> > 
> > 
> > ....Sorry, how do I download it? .
> 
> You can compile the latest source from the github or wait for the next github release

Sorry to bother you again, after I completed the compilation, no jar appeared.
