### ISSUE TITLE
Unuseable CLI

### ISSUE THREAD

**Issue by TIMER-err** [skidfuscatordev/skidfuscator-java-obfuscator#54]
1.
My cmd line:
>"%JAVA_HOME%/bin/java" -jar Skidfuscator.jar obfuscate cli -li=libs -ex=exemption.txt loader.jar

error:
>Unmatched argument at index 4: 'loader.jar'
>Usage: <main class> obfuscate [-hV] [-dbg] [-fuckit] [-notrack] [-ph]
>                              [-cfg=<config>] [-ex=<exempt>] [-li=<libFolder>]
>                              [-o=<output>] [-rt=<runtime>] <input>
>Obfuscates and runs a specific jar
>      <input>               The file which will be obfuscated.
>      -cfg, --config=<config>
>                            Path to the config file
>      -dbg, --debug         Do not use!
>      -ex, --exempt=<exempt>
>                            Path to the exempt file
>      -fuckit, --fuckit     Do not use!
>  -h, --help                Show this help message and exit.
>      -li, --libs=<libFolder>
>                            Path to the libs folder
>      -notrack, --notrack   If you do not wish to be part of analytics!
>  -o, --output=<output>     Path to the output jar location
>      -ph, --phantom        Declare if phantom computation should be used
>      -rt, --runtime=<runtime>
>                            Path to the runtime jar
>  -V, --version             Print version information and exit.

2.
My cmd line:
>"%JAVA_HOME%/bin/java" -jar Skidfuscator.jar obfuscate -li=libs -ex=exemption.txt loader.jar

error:
>java.lang.StringIndexOutOfBoundsException: String index out of range: -1
>        at java.lang.String.substring(String.java:1967)
>        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:173)
>        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:22)
>        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
>        at picocli.CommandLine.access$1300(CommandLine.java:145)
>        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
>        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
>        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
>        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
>        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
>        at picocli.CommandLine.execute(CommandLine.java:2078)
>        at dev.skidfuscator.obfuscator.SkidfuscatorMain.main(SkidfuscatorMain.java:75)

3.
My cmd line:
>"%JAVA_HOME%/bin/java" -jar Skidfuscator.jar -li=libs -ex=exemption.txt loader.jar

error:
>Unknown options: '-li=libs', '-ex=exemption.txt', 'loader.jar'
>Usage: <main class> [-hV] [COMMAND]
>Shows all the options
>  -h, --help      Show this help message and exit.
>  -V, --version   Print version information and exit.
>Commands:
>  obfuscate  Obfuscates and runs a specific jar

4.
My cmd line:
>"%JAVA_HOME%/bin/java" -jar Skidfuscator.jar obfuscate -li=libs loader.jar

It works, but this is not the result I hope for.

It has driven me mad, help me, plz!
😭

**Comment by tmdakm** [comment]
idk the reason for 2, but for 1 and 3, u can try replacing 'loader. jar' with an absolute path

**Comment by terminalsin** [comment]
fixed in 2.0.10
